[aws]
disabled = true

[directory]
disabled = false
style = "bold blue"
truncation_length = 1

[git_branch]
disabled = false
style = "bold #6c71c4"

[golang]
disabled = false
style = "bold cyan"

[hostname]
disabled = false
ssh_only = false
style = "bold purple"

[package]
disabled = true

[python]
disabled = false
style = "bold #cb4b16"

[rust]
disabled = false
style = "red"

[username]
disabled = false
format = "[$user]($style) at "
show_always = true
style_root = "bold black"
style_user = "bold red"
