[aws]
disabled = true

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"

[directory]
disabled = false
style = "bold blue"
truncation_length = 1

[git_branch]
disabled = false
style = "bold #6c71c4"

[golang]
disabled = false
format = "[\\($symbol$version\\)]($style) "
style = "bold cyan"

[hostname]
disabled = false
ssh_only = false
style = "bold purple"

[nodejs]
disabled = false
symbol = "⬢ "
format = "[\\($symbol$version\\)]($style) "

[package]
disabled = true

[python]
disabled = false
format = "[\\($symbol$version( \\($virtualenv\\))\\)]($style) "
style = "bold #cb4b16"

[rust]
disabled = false
format = "[\\($symbol$version\\)]($style) "

[username]
disabled = false
format = "[$user]($style) at "
show_always = true
style_root = "bold black"
style_user = "bold red"
