[directory]
disabled = false
truncation_length = 1
style = "blue"

[git_branch]
disabled = false
style = "#6c71c4"

[git_commit]
disabled = false
style = "green"

[git_state]
disabled = false
style = "yellow"

[git_status]
disabled = false
style = "red"

[hostname]
disabled = false
ssh_only = false
style = "purple"

[nodejs]
disabled = false
style = "green"

[python]
disabled = false
style = "#cb4b16"

[username]
disabled = false
format = "[$user]($style) at "
show_always = true
style_root = "red bold"
style_user = "red"
